#+TITLE: Opg3
#+PROPERTY: session *R*
#+PROPERTY: results output
#+AUTHOR: Ali Kadum Hassan, Frederik Henriques Altmann, Gustav Emil Mark-Hansen

* OPGAVE 1

** a
\begin{verbatim}
Hej
\end{verbatim}

#+begin_src R :exports results :results graphics :file img.png
hist(rnorm(100))
#+end_src

#+results:
file:img.png

Some text
$e = mc^2$

** a
Chancen for at få X kast der lander på krone i træk, er:
$(\frac{1}{2})^X$

Skrevet i R:
\begin{verbatim}
pmf = \(throws) 0.5^throws
\end{verbatim}
** b
Profiten $f(X)$ er givet ved $f(a, X) = a2^X - a$

Skrevet i R:
\begin{verbatim}
profit = \(buyin, throws) buyin * 2^(throws) - buyin
\end{verbatim}
** c
\begin{align}
E(X) = \sum_{n=1}^\infty |f(b,n)|p(n) = \sum_{n=1}^\infty b \\
|f(x)|p(x) = b2^{x+1}0.5^x = b \\
\sum_{n=1}^\infty |f(b,n)|p(n) = \sum_{n=1}^\infty b = \infty
\end{align}

Da $E(X)$ divergerer mod positiv uendelig har spillet ikke noget forventet udfald.
* 2
** a
Da hele pmf $p$, bortset fra $p(x=-1,y=3)$ er kendt kan $z$ beregnes ved at isolere.

| p(x, y) | y = −1 | y = 1 | y = 3 |
| x = −1  |    0.1 |   0.1 | z     |
| x = 1   |    0.3 |  0.05 | 0.05  |

\begin{align}
\int p(x,y) &= 1 \\
1 &= 0.1 + 0.1 + 0.3 + 0.05 + 0.05 + z = 0.6 + z \\
z &= 1 - 0.6 = 0.4
\end{align}

Skrevet i R:
\begin{verbatim}
p <- matrix(c(0.1,0.1,z,0.3,0.05,0.05), 2, 3, TRUE)
z <- 1 - (0.1 + 0.1 + 0.3 + 0.05 + 0.05)
\end{verbatim}
** b
Beregn den forventede gevinst

\begin{align}
E[X+Y] &= E[X] + E[Y] \\
E[X] &= -1*0.6 + 1*0.4 = -0.2 \\
E[Y] &= -1*0.4 + 1*0.15 + 3*0.45 = 1.1 \\
E[X+Y] &= 1.1 - 0.2 = 0.9
\end{align}

Skrevet i R (fortsat):

\begin{verbatim}
x <- -sum(p[1,]) + sum(p[2,])
y <- -sum(p[,1]) + sum(p[,2]) + 3*sum(p[,3])
E <- x + y # Forventede gevinst
\end{verbatim}
** c
beregn kovariansen mellem X og Y. Er X og Y uafhængige?

Skrevet i R (fortsat):
\begin{verbatim}
xy <- c(z, 0.3+0.1, 0.15, 0.05)
-3*xy[1]+ (-1)*xy[2] +xy[3]+3*xy[4] #-> E(xy) = -1.3
-1.3-(mean(x)*mean(y)) #->              Cov(x,y)= -1.08
\end{verbatim}

Hvilket betyder at de er afhængige af hinanden, da cov /= 0 og at de 2 bevæger sig modsat af hinanden

* 3
** a
Vi ved at hvis $A$ har et udfald som er givet,
har den altid en sandsynlighed $1$ betinget at det er udfaldet.

| CPT            |   A=1 |   A=0 |
| P(T=1 givet A) | 0.998 |     a |
| P(T=0 givet A) |     b | 0.993 |
| sum            |     1 |     1 |

Derfor må $a = 1-0.993$ og $b=1-0.998$.

| CPT            |   A=1 |   A=0 |
| P(T=1 givet A) | 0.998 | 0.007 |
| P(T=0 givet A) | 0.002 | 0.993 |
| sum            |     1 |     1 |

Sandsynligheden for at have en peanut allergi er $P(A = 1) = 0.01$, 1%,
samt $P(A = 0) = 0.99$, 99% for ikke at have allergien.

Da
\[P(A|B) = \frac{P(A \union B)}{P(B)}\]
\[P(A \union B) = P(A|B)\cdot P(B)\]

kan en *pmf* beregnes.

#+begin_comment
#+begin_src R
CPT <- matriX(c(0.998,  0.002,  0.007,  0.993), ncol=2)
PMF <- matrix(c(CPT[,1] * 0.01, CPT[,2] * 0.99), ncol = 2)
sum(PMF[1,])
sum(PMF[2,])
sum(PMF)
#+end_src
#+end_comment

| PMF |     A=1 |     A=0 |     sum |
| T=1 | 0.00998 | 0.00693 | 0.01691 |
| T=0 | 0.00002 | 0.98307 | 0.98309 |
| sum |    0.01 |    0.99 |       1 |

Summen af rækkerne er så hhv. $P(T=1)$ og $P(T=0)$.
** b
Sandsynligheden for ikke at have allergien givet en negativ test er:
\[P(A=0|T=0)=\frac{P(A=0,T=0)}{P(T=0)}=\frac{0.98307}{0.98309}= 0.9999797\]
** c
Sandsynligheden for at have allergien givet en positiv test er:
\[P(A=1|T=1)=\frac{P(A=1,T=1)}{P(T=1)}=\frac{0.00998}{0.01}= 0.998\]

* 4
** a
